config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

get 'events/new'

get 'events/show'

get 'sessions/new'

root 'static_pages#home'

    get     '/signup',  to: 'users#new'
    post    '/signup',  to: 'users#create'
    get     '/login',   to: 'sessions#new'
    post    '/login',   to: 'sessions#create'
    delete  '/logout',  to: 'sessions#destroy'

resources :users
resources :events do
	post 'attend', on: :member

end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

validates :description, presence: true
validates :date, presence: true
validates :location, presence: true

belongs_to :user

=begin 
belongs_to creator, class_name: ‘User’
has_many :invitations
has_many :attendees, through: :invitations
=end 
 
end

app/models/user.rb
class User < ApplicationRecord

validates :name, presence: true, uniqueness: true
has_many :events

=begin  
has_many :created events, class_name: ‘Event’
has_many :invitations
has_many :attented_events, through: :invitations 
=end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end
  
  def new
    @event = Event.new
  end
  
  def create
    @event = current_user.events.new(event_params)
    if @event.save
      flash[:success] = "Evénement enregistré"
      redirect_to @event
    else
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def attend
    @event.attendees << current_user
    @event.save
  end
  
  private
  def event_params
    params.require(:event).permit(:description, :date, :place)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
      user = User.find_by(name: params[:session][:name])
      if user
          log_in user
          redirect_back_or user
      else
          render 'new'
      end
  end

  def destroy
      log_out
      redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :logged_in_user, only: [:index, :edit, :update]
    before_action :correct_user,   only: [:edit, :update]
    
  def index
      @users = User.all
  end
    
  def new
      @user = User.new
  end
    
  def create
      @user = User.new(user_params)
          if @user.save
              log_in @user
              flash[:success] = "Bienvenue sur Eventbrite"
              redirect_to @user
          else
              render 'new'
          end
  end

  def edit
      @user = User.find(params[:id])
  end
    
  def update
      @user = User.find(params[:id])
      if @user.update_attributes(user_params)
      flash[:success] = "Profil modifié"
      redirect_to @user
      else
          render 'edit'
      end
  end

  def show
      @user = User.find(params[:id])
  end
    
  def destroy
      User.find(params[:id]).destroy
      flash[:success] = "User deleted"
      redirect_to users_url
  end
    
    private
    def user_params
        params.require(:user).permit(:name)
    end
    
  def logged_in_user
      unless logged_in?
          store_location
          flash[:danger] = "Veuillez vous connecter"
          redirect_to login_url
      end
  end
    
  def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
    session[:user_id] = user.id
    end
    
    def current_user?(user)
    user == current_user
    end
    
    def current_user
    @current_user ||= User.find_by(id: session[:user_id])
    end
    
    def logged_in?
    !current_user.nil?
    end
    
    def log_out
    session.delete(:user_id)
    @current_user = nil
    end
    
    def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
    end
    
    def store_location
    session[:forwarding_url] = request.original_url if request.get?
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<% provide(:title, 'Evénements') %>
<h1>Evénements</h1>

<ul class="events">
  <% @events.each do |event| %>
    <h3>
      <%= link_to event.description, event %>
        </h3> Créé par : <%= link_to event.user.name, event.user %>
  <% end %>
</ul>

app/views/events/new.html.erb
<% provide(:title, "New event") %>
<h1>New event</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@event, url: events_path) do |f| %>

      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>
      
      <%= f.label :date %>
      <%= f.date_field :date, class: 'form-control' %>
      
      <%= f.label :place %>
      <%= f.text_field :place, class: 'form-control' %>

      <%= f.submit "New event", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<% provide(:title, @event.description) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @event.description %> 
      </h1>
       <p>
       <%= @event.date %>
       </p>
       <p>
       <%= @event.place %>
       </p>
       <p>
       <strong>Créateur:</strong>
       <%= link_to @event.user.name, @event.user %></p>
    </section>
    
     <%= button_to 'Participer', attend_event_path(@event), method: :post, confirm: 'really?' %>
  </aside>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "eventbrite", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Events <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Events", events_path %></li>
              <li><%= link_to "New", new_event_path %></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profil", current_user %></li>
              <li><%= link_to "Edit", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">

       <% flash.each do |message_type, message| %>
       <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>

      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Find your next experience !</h1>

  <h2>
    Discover amazing event or create your own !
  </h2>

  <%= link_to "Sign up now !", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit users") %>
<h1>Modifier votre profil</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.submit "Save", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Users') %>
<h1>Users</h1>

<ul class="users">
  <% @users.each do |user| %>
    <h3>
      <%= link_to user.name, user %>
        </h3>
  <% end %>
</ul>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>


      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.submit "Create account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>

<h1>Events created</h1>

<ul class="events">
  <% @user.events.each do |event| %>
    <h3>
      <%= link_to event.description, event %>
        </h3>
  <% end %>
</ul>